version: '3.3'
services:
    mysite:
        build: ./
        container_name: VincePorter
        restart: always
        networks:
            - galactica
        ports:
            - '5000:3000'
        volumes:
            - ./:/app
networks:
    galactica:
        name: galactica